language: python

sudo: false

matrix:
  fast_finish: true
  include:
    - env: TOX_ENV=py27-django15
      python: 2.7
      dist: trusty
    - env: TOX_ENV=py34-django15
      python: 3.4
      dist: trusty

    - env: TOX_ENV=py27-django16
      python: 2.7
      dist: trusty
    - env: TOX_ENV=py34-django16
      python: 3.4
      dist: trusty

    - env: TOX_ENV=py27-django17
      python: 2.7
      dist: trusty
    - env: TOX_ENV=py34-django17
      python: 3.4
      dist: trusty

    - env: TOX_ENV=py27-django18
      python: 2.7
      dist: trusty
    - env: TOX_ENV=py34-django18
      python: 3.4
      dist: trusty
    - env: TOX_ENV=py35-django18
      python: 3.5
      dist: xenial
    - env: TOX_ENV=py36-django18
      python: 3.6
      dist: xenial

    - env: TOX_ENV=py27-django19
      python: 2.7
      dist: trusty
    - env: TOX_ENV=py34-django19
      python: 3.4
      dist: trusty
    - env: TOX_ENV=py35-django19
      python: 3.5
      dist: xenial
    - env: TOX_ENV=py36-django19
      python: 3.6
      dist: xenial

    - env: TOX_ENV=py27-django110
      python: 2.7
      dist: trusty
    - env: TOX_ENV=py34-django110
      python: 3.4
      dist: trusty
    - env: TOX_ENV=py35-django110
      python: 3.5
      dist: xenial
    - env: TOX_ENV=py36-django110
      python: 3.6
      dist: xenial

    - env: TOX_ENV=py27-django111
      python: 2.7
      dist: trusty
    - env: TOX_ENV=py34-django111
      python: 3.4
      dist: trusty
    - env: TOX_ENV=py35-django111
      python: 3.5
      dist: xenial
    - env: TOX_ENV=py36-django111
      python: 3.6
      dist: xenial

    - env: TOX_ENV=py35-django20
      python: 3.5
      dist: xenial
    - env: TOX_ENV=py36-django20
      python: 3.6
      dist: xenial
    - env: TOX_ENV=py37-django20
      python: 3.7
      dist: xenial
    - env: TOX_ENV=py38-django20
      python: 3.8
      dist: xenial

    - env: TOX_ENV=py35-django21
      python: 3.5
      dist: xenial
    - env: TOX_ENV=py36-django21
      python: 3.6
      dist: xenial
    - env: TOX_ENV=py37-django21
      python: 3.7
      dist: xenial
    - env: TOX_ENV=py38-django21
      python: 3.8
      dist: xenial

    - env: TOX_ENV=py35-django22
      python: 3.5
      dist: xenial
    - env: TOX_ENV=py36-django22
      python: 3.6
      dist: xenial
    - env: TOX_ENV=py37-django22
      python: 3.7
      dist: xenial
    - env: TOX_ENV=py38-django22
      python: 3.8
      dist: xenial

    - env: TOX_ENV=py36-django30
      python: 3.6
      dist: xenial
    - env: TOX_ENV=py37-django30
      python: 3.7
      dist: xenial
    - env: TOX_ENV=py38-django30
      python: 3.8
      dist: xenial

    - env: TOX_ENV=py36-django31
      python: 3.6
      dist: xenial
    - env: TOX_ENV=py37-django31
      python: 3.7
      dist: xenial
    - env: TOX_ENV=py38-django31
      python: 3.8
      dist: xenial

    - env: TOX_ENV=py36-django32
      python: 3.6
      dist: xenial
    - env: TOX_ENV=py37-django32
      python: 3.7
      dist: xenial
    - env: TOX_ENV=py38-django32
      python: 3.8
      dist: jammy
    - env: TOX_ENV=py39-django32
      python: 3.9
      dist: jammy
    - env: TOX_ENV=py310-django32
      python: 3.10
      dist: jammy

    - env: TOX_ENV=py38-django40
      python: 3.8
      dist: jammy
    - env: TOX_ENV=py39-django40
      python: 3.9
      dist: jammy
    - env: TOX_ENV=py310-django40
      python: 3.10
      dist: jammy

    - env: TOX_ENV=py38-django41
      python: 3.8
      dist: jammy
    - env: TOX_ENV=py39-django41
      python: 3.9
      dist: jammy
    - env: TOX_ENV=py310-django41
      python: 3.10
      dist: jammy
    - env: TOX_ENV=py311-django41
      python: 3.11
      dist: jammy

    - env: TOX_ENV=py38-django42
      python: 3.8
      dist: jammy
    - env: TOX_ENV=py39-django42
      python: 3.9
      dist: jammy
    - env: TOX_ENV=py310-django42
      python: 3.10
      dist: jammy
    - env: TOX_ENV=py311-django42
      python: 3.11
      dist: jammy

    - env: TOX_ENV=py310-djangomaster
      python: 3.10
      dist: jammy
    - env: TOX_ENV=py311-djangomaster
      python: 3.11
      dist: jammy

#  # django22 and django-master can only be installed into xenial images
#    - python: 3.7
#      dist: xenial
#      sudo: true
#
#    - python: 3.6
#      env: DIST=trusty
#
#    - python: 3.6
#      dist: xenial
#      sudo: true
#      env: DIST=xenial
#
#    - python: 2.7
#    - python: 3.5
#    - python: 3.4
#    # tox and tox-travis refuse to run on Python 3.3
#    # Also various versions of Django on Python 3.3 are reporting
#    # django/utils/html_parser.py: AttributeError: module 'html.parser' has no attribute 'HTMLParseError'
#
#    - python: 3.5
#      env: TOX_ENV=py35-django22
#      install: pip install tox
#      dist: xenial
#      sudo: true
#
#    - python: 3.6
#      env: TOX_ENV=py36-django22
#      install: pip install tox
#      dist: xenial
#      sudo: true
#
#    - python: 3.6
#      env: TOX_ENV=py36-django-master
#      install: pip install tox
#      dist: xenial
#      sudo: true
#
#    - python: 3.7
#      env: TOX_ENV=py37-django-master
#      install: pip install tox
#      dist: xenial
#      sudo: true

  allow_failures:
    - env: TOX_ENV=py35-djangomaster
    - env: TOX_ENV=py36-djangomaster
    - env: TOX_ENV=py37-djangomaster

install:
  - pip install tox-travis

script:
  - tox -e $TOX_ENV

after_success:
  - pip install coveralls
  - coveralls
